apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: argo-application-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/PrabKang/juice-shop-helm.git
    targetRevision: HEAD
    path: prod
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNameSpace=true

    automated:
      selfHeal: true
      prune: true