# values.yaml

replicaCount: 1

image:
  repository: bkimminich/juice-shop
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
